name: Selenium Suite Runner

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - BTP
          - GCP

      suiteType:
        description: "Select Test Suite"
        required: true
        type: choice
        options:
          - Functional
          - Negative
          - Regression

      browser:
        description: "Select Browser"
        required: true
        type: choice
        options:
          - chrome
          - edge
          - both

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ${{ github.event.inputs.browser == 'both' && fromJson('["chrome","edge"]') || fromJson(format('["{0}"]', github.event.inputs.browser)) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Set Environment and Suite
        run: |
          if [ "${{ github.event.inputs.environment }}" == "BTP" ]; then
            echo "WORK_DIR=Selenium/BTP" >> $GITHUB_ENV
            if [ "${{ github.event.inputs.suiteType }}" == "Functional" ]; then
              echo "SUITE_PATH=src/test/resources/testrunners/assetInspectionFunctionalRunnerFile.xml" >> $GITHUB_ENV
            elif [ "${{ github.event.inputs.suiteType }}" == "Negative" ]; then
              echo "SUITE_PATH=src/test/resources/testrunners/assetInspectionNegativeRunnerFile.xml" >> $GITHUB_ENV
            else
              echo "SUITE_PATH=src/test/resources/testrunners/assetInspectionRegressionRunnerFile.xml" >> $GITHUB_ENV
            fi
          else
            echo "WORK_DIR=Selenium/GCP" >> $GITHUB_ENV
            if [ "${{ github.event.inputs.suiteType }}" == "Functional" ]; then
              echo "SUITE_PATH=src/test/resources/testrunners/gcpFunctionalRunnerFile.xml" >> $GITHUB_ENV
            elif [ "${{ github.event.inputs.suiteType }}" == "Negative" ]; then
              echo "SUITE_PATH=src/test/resources/testrunners/gcpNegativeRunnerFile.xml" >> $GITHUB_ENV
            else
              echo "SUITE_PATH=src/test/resources/testrunners/gcpRegressionRunnerFile.xml" >> $GITHUB_ENV
            fi
          fi

      - name: Run Selected TestNG Suite
        working-directory: ${{ env.WORK_DIR }}
        run: mvn clean test -Dsurefire.suiteXmlFiles=${{ env.SUITE_PATH }} -Dbrowser=${{ matrix.browser }}
