name: Run WDIO Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * 0-4'

jobs:
  wdio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 \
            libgbm-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2t64 \
            libxtst6 \
            xdg-utils \
            xvfb

      - name: Run WDIO tests + prepare logs
        env:
          CI: true
        run: |
          mkdir -p logs
          npx wdio run wdio.conf.ts --maxInstances 4 2>&1 | tee logs/console.log || true
          
          echo "Splitting logs by worker..."
          node scripts/split-wdio-logs.cjs || true

      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          
      - name: Upload WDIO logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wdio-logs
          path: logs

      - name: Deploy Allure Report & Add Summary Link
        if: always()
        run: |
          npm install -g gh-pages
          gh-pages -d allure-report -b gh-pages -f

          echo "## 🧪 Allure Report" >> $GITHUB_STEP_SUMMARY
          echo "Open report: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Complete job
        run: echo "Workflow finished"
